### ISSUE TITLE
wiring diagram

### ISSUE THREAD

**Issue by timber77** [maschinenbauerbauer/adcmxl-spi-python#1]
Hi
Have you still got your wiring diagram or some info on how you connected the sensor?

Thanks a lot

**Comment by maschinenbauerbauer** [comment]
Hi, I'm sorry, but since my workplace change I lost access to the original wiring diagram file which I wanted to include in the Readme-File. 
But I hope this clears things up: 
We connected a 3-LED-RGB-Light with four pin (one for each LED and a common ground) to the raspberry pi on pins 26 (red), 19 (yellow) & 13 (green). These are optional, but you have to adapt the code to fit your needs in that case. 

The ADCMXL was connected with the help of the breakout board you can find here: [Breakout Board](https://www.digikey.de/de/products/detail/analog-devices-inc/ADCMXL-BRKOUT-PCBZ/10274174)
Just follow the circuit boards pins and compare to the Table 5 in the datasheet (page 8/50) here: [Datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/adcmxl3021.pdf
)
I will now get into detail about what to connect to whicht pin. The first value is always the sensor side, and the second is Raspberry Pi side (e.g. SENSOR (PIN) -> RPI (PIN) ) (im referring to pins, not GPIO Ports here in the parantheses! see [pinout.xyz](https://pinout.xyz/))
We connected GND (1) -> GND (6),  VDD (8) -> 5V (2), SCLK (13) -> GPIO11 (23), CS (14) -> CE0 (24), DIN (11) -> GPIO9 (21), DOUT (12) -> GPIO10 (19) and BUSY (5) -> GPIO22 (15). 

As I'm recalling this from pure memory, there could be faulty connections in this. Maybe I switched the Pins for DIN or DOUT, I'm not sure anymore whether the ADCMXL refers to itself as the master or the RPi. I guessed it refers to the Pi as master. But just try around. 

I also remember changing some settings on the RPi to get it to work but I could not figure out, whether it made an improvement because we switched mid-project from RPi3B to RPi4: [Issue SPI Speed](https://github.com/raspberrypi/linux/issues/3381#issuecomment-567521707)

I hope this helps you with your project. Don't hesitate to ask again!

**Comment by timber77** [comment]
Hi, I actually got it running on the RPI 3B+ in the meantime: As a comparison and for future reference here are my connections(in bold the differences):
GND -> GND(6), **VDD -> 3v3(1)**, SCLK -> GPIO11(23), **CS -> CE0(24)**, **DIN -> GPIO10(19)**, DOUT -> GPIO9(21), BUSY -> GPIO22(15), **RST -> 3v3(17)**. I used the [ADcmXL FX3 Interface](https://www.mouser.ch/new/analog-devices/adi-eval-adcm-kit/) board to connect it.
So far I had no problems with the SPI clock speed but thanks for the hint.
Thanks a lot for your help and your code
